# Generated by Django 3.2.23 on 2024-02-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='links',
            new_name='link',
        ),
    ]
